### ISSUE TITLE
Factoid Graph Range

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#58]
Restricting the range of the x axis on the factoid graph "# of Facts" to only display occurrences of significant data would make it a lot more legible.

For example, I factoid all of the lead actors in all the movies I watch. and my "# of Facts" graph has about 40 names listed across the x axis which makes it hard to read and check their frequency. If it selectively chose the Top 10 actors whose names occurred the most frequently it would improve on the data visualization  .

**Comment by NonlinearFruit** [comment]
I tried adding additional range adjusting tools a while ago but it made the chart tab really crowded. Any ideas on how to format the UI so that the controls don't make the chart tab more intimidating?

![image](https://user-images.githubusercontent.com/6962125/31347671-12012e7e-aceb-11e7-88aa-68eef36ed053.png)

**Comment by JUG1T3R** [comment]
You could add "Number of Months" (for category), and "Max/Min" for Factoid into the .config file like how it is for the first bar graph (Past ____ Days).

**Comment by NonlinearFruit** [comment]
So for **# of Facts**, a way to set the min and max frequency threshold.

**Comment by NonlinearFruit** [comment]
Done

![peek 2017-12-05 09-45](https://user-images.githubusercontent.com/6962125/33612942-319583b0-d9a1-11e7-996c-eed27f430757.gif)
