### ISSUE TITLE
Time Filter for Chart Tab

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector#59]
It would be cool to have further flexibility to manipulate the chart tab. Now that I have 10 months worth of data being able to select how many months of data I'd like to view would give a more comprehensive look at the mix of media I consume.

Essentially it'd be adding a 1 Month, 3 Month, 6 Month, 1 Year, or All-Time drop down list or radio that would update all the charts on the page. 

This change could make it a lot easier to see how many of each type of media you've consumed each month. (ex. I watched 31 movies, or read 180 comics)

**Comment by NonlinearFruit** [comment]
I'm thinking we should add a popup on each chart that lets you edit it in some way. What should be editable for each chart?

**Comment by JUG1T3R** [comment]
-I think being able to select a date range would be super helpful, particularly for **Category Size** and **Monthly Totals**. 
-Something I would find useful for **Monthly Totals** (not a chart option, but just in general) would be if it were traceable. So you could see the exact number of each month when you hover over its point.
-An option to display a normal distribution curve would be neat for the **Rating Distribution** graph
-The **# of Facts** graph really needs a way to limit the number of facts being displayed. (keeping track of actors in movies creates a giant unreadable mess for me currently)

**Comment by NonlinearFruit** [comment]
- For **Category Size** and **Monthly Totals** would the past `1 Month`, `3 Months`, `6 Months`, `1 Year` and `All Time` be adequate? I think that would be the simplest for users, instead of picking dates.
 - I'm not sure if overlaying a curve is possible/easy, would overlaying/underlaying something like [this](http://psy.swansea.ac.uk/staff/carter/gnuplot/frequency.png) work?
 - **# of Facts** has its own issue here: #58 

For future reference, here is a solution to tracing **Monthly Totals**:
https://stackoverflow.com/a/14623439/4769802

**Comment by NonlinearFruit** [comment]
Trace-ability is done. (Not sure how to fix high and low labels getting cut off)

![peek 2017-12-02 22-16](https://user-images.githubusercontent.com/6962125/33521951-7b48a31a-d7ae-11e7-9adc-a62b401bd82e.gif)

**Comment by NonlinearFruit** [comment]
I have postponed the curve. The chart tab needs to be refactored so that improvements are easier. It is getting really ugly. 

However, I have implemented time controls for Category Size and Monthly Totals and count controls for # of Facts. Double click the chart to access them.

![peek 2017-12-05 09-45](https://user-images.githubusercontent.com/6962125/33612893-054c3ccc-d9a1-11e7-9211-99cb879d7e38.gif)
